# standard jekyll configuration

content_editable: true
content_revision_history: true
content_questions_comments: true
url: "http://wet-boew.github.io/wet-boew-jekyll/"
repo_name: "wet-boew-jekyll"
branch: "master"

#global settings, no need to change these
root_url: "http://wet-boew.github.io/wet-boew-jekyll/"
org_name: "wet-boew"
prose_url: "http://prose.io"

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ['README.md']

